### ISSUE TITLE
CI/CD test scenarios failing intermittently due to nodemanager service failure

### ISSUE THREAD

**Issue by sanjaymantoor** [wls-eng/arm-oraclelinux-wls#160]
Following test scenarios were failing intermittently 

- verify-services
- verify-wls-access

**Comment by sanjaymantoor** [comment]
It is noticed that  wls_nodemanager services are failing due to following exception at NodeManager log file.

java.net.UnknownHostException: adminServerVM: Name or service not known
        at java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method)
        at java.net.InetAddress$2.lookupAllHostAddr(InetAddress.java:928)
        at java.net.InetAddress.getAddressesFromNameService(InetAddress.java:1322

After investigation, it is better to wait wls_admin and wls_nodemanager services till network service is available. Also in case of service failure, it should be restarted automatically
