### ISSUE TITLE
On wls14 and java 11: exception happens when adding nodes to cluster with add-node template

### ISSUE THREAD

**Issue by galiacheng** [wls-eng/arm-oraclelinux-wls#165]
Offer: cluster
Exception happen while deploying add-node template to add nodes to weblogic cluster on wls 14 and java 11.
with:
app gateway: enable
aad: enable
db: enable

Error:
```
Enrolling this machine with the domain directory at /u01/domains/wlsd ...
This Exception occurred at Tue Sep 08 08:20:52 UTC 2020.
weblogic.net.http.HttpUnauthorizedException: Server authentication required but WWW-Authenticate header is null
No stack trace available.
```

**Comment by galiacheng** [comment]
This error happens because WebLogic version and JDK version in new node is wls 12, JDK 8. If using the some images in new node, the error can not reproduce.
Will close it.

If we have requirement to running WebLogic Cluster with nodes of different WebLogic version and Java version, create a new issue for it.

**Comment by galiacheng** [comment]
Deploy tool version is too low to support JDK 11 in add-node script, re open this issue.

**Comment by galiacheng** [comment]
File "/u01/domains/enroll-server.py", line 2, in <module>
    nmEnroll('/u01/domains/wlsd','/u01/domains/wlsd/nodemanager')
  File "<iostream>", line 1710, in nmEnroll
  File "<iostream>", line 548, in raiseWLSTException
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
        at java.base/java.lang.Class.newInstance(Class.java:584)
        at org.python.core.PyObject.proxyInit(PyObject.java:200)
        at org.python.core.Deriveds.dispatch__init__(Deriveds.java:24)
        at org.python.core.PyObjectDerived.dispatch__init__(PyObjectDerived.java:1112)
        at org.python.core.PyType.type___call__(PyType.java:1822)
        at org.python.core.PyType.__call__(PyType.java:1805)
        at org.python.core.PyObject.__call__(PyObject.java:480)
        at org.python.core.PyObject.__call__(PyObject.java:484)
        at org.python.pycode._pyx5.raiseWLSTException$28(<iostream>:548)
        at org.python.pycode._pyx5.call_function(<iostream>)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyBaseCode.call(PyBaseCode.java:139)
        at org.python.core.PyFunction.__call__(PyFunction.java:413)
        at org.python.pycode._pyx33.nmEnroll$102(<iostream>:1712)
        at org.python.pycode._pyx33.call_function(<iostream>)
...
  at org.python.pycode._pyx32.f$0(/u01/domains/enroll-server.py:3)
        at org.python.pycode._pyx32.call_function(/u01/domains/enroll-server.py)
        at org.python.core.PyTableCode.call(PyTableCode.java:171)
        at org.python.core.PyCode.call(PyCode.java:18)
        at org.python.core.Py.runCode(Py.java:1614)
        at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
        at weblogic.management.scripting.WLST.main(WLST.java:192)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at weblogic.WLST.main(WLST.java:47)
Caused by: weblogic.security.internal.encryption.EncryptionServiceException: com.rsa.jsafe.JSAFE_PaddingException: Invalid padding.
        at weblogic.security.internal.encryption.JSafeEncryptionServiceImpl.decryptBytes(JSafeEncryptionServiceImpl.java:144)
        at weblogic.security.internal.encryption.JSafeEncryptionServiceImpl.decryptBytes(JSafeEncryptionServiceImpl.java:177)
        at weblogic.security.internal.encryption.ClearOrEncryptedService.decryptBytes(ClearOrEncryptedService.java:129)
        at weblogic.management.scripting.NodeManagerService.decrypt(NodeManagerService.java:88)
        at weblogic.management.scripting.NodeManagerService.nmEnrollMachine(NodeManagerService.java:130)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
__main__.WLSTException: Error occurred while performing nmEnroll : Problem occurred while encrypting a value : com.rsa.jsafe.JSAFE_PaddingException: Invalid padding.
Use dumpStack() to view the full stacktrace :
