### ISSUE TITLE
WLS 14.1.1.0 exception during managed server creation

### ISSUE THREAD

**Issue by edburns** [wls-eng/arm-oraclelinux-wls#89]
https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1127971

Hello experts,

 

I got an exception while creating managed server in cluster offer, with environment:

weblogic version 14.1.1.0.0
JDK 11_07
Oracle Linux 7.6
The issue cannot be reproduced on image ‘WebLogic Server 12.2.1.3.0 and JDK8u131 on Oracle Linux 7.4’ with the same script, it may be weblogic 14 related.

 

Error message (pls find attachment error.txt for more information):

 File "/u01/domains/add-server.py", line 21, in <module>

    nmEnroll('/u01/domains/wlsd','/u01/domains/wlsd/nodemanager')

  File "<iostream>", line 1710, in nmEnroll

  File "<iostream>", line 548, in raiseWLSTException

… …

Caused by: weblogic.security.internal.encryption.EncryptionServiceException: com.rsa.jsafe.JSAFE_PaddingException: Invalid padding. 

 

I open 7001 and 7002 with firewall-cmd on adminVM to make sure weblogic server is accessible, and configured managed vm mspVM1 with this script.

I found workaround from oracle support document,  but it didn’t work for me.

 

This resource group has environment for quick check:

Subscription: Oracle Enterprise Java

Resource group: oraclevm-cluster-cli-0519

Admin Server: http:// wls0-b10a4542b3-wlsd.eastus.cloudapp.azure.com:7001/console( username/password: weblogic/APB9faTHAPB9faTH)

Username/password for all vms: weblogic/wlsEng@aug2019

 

Do you have any idea to solve this error by changing configuration?

Thank you very much!

 

Regards,

Galia

**Comment by edburns** [comment]
```

devdiv
/
DevDiv
/
Boards
/
Work items
Search

Account manager for Edward Burns

















TASK 1127971
1127971
Error happens during creating managed server with script on WebLoigc 14.1.1.0.0
Focus on the selected item to change the value via a combo box
Haixia Cheng
0 comments
State
Committed
Reason
Committed
Area
DevDiv\Java on Azure\Open Standard Enterprise Java (Java EE) on Azure
Iteration
DevDiv\OneVS\CY20-H1\Q2\Sprint 170
Updated by Haixia Cheng: 9h ago
MainTenets (3) (1)
Add attachment
error.txt
5K5/20/2020 10:11 AM 
Traceback (most recent call last):
File "/u01/domains/add-server.py", line 21, in <module>
nmEnroll('/u01/domains/wlsd','/u01/domains/wlsd/nodemanager')
File "<iostream>", line 1710, in nmEnroll
File "<iostream>", line 548, in raiseWLSTException
at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
at java.base/java.lang.Class.newInstance(Class.java:584) at org.python.core.PyObject.proxyInit(PyObject.java:200) at org.python.core.Deriveds.dispatch__init__(Deriveds.java:24) at org.python.core.PyObjectDerived.dispatch__init__(PyObjectDerived.java:1112) at org.python.core.PyType.type___call__(PyType.java:1822) at org.python.core.PyType.__call__(PyType.java:1805) at org.python.core.PyObject.__call__(PyObject.java:480)
at org.python.core.PyObject.__call__(PyObject.java:484)
at org.python.pycode._pyx5.raiseWLSTException$28(<iostream>:548)
at org.python.pycode._pyx5.call_function(<iostream>)
at org.python.core.PyTableCode.call(PyTableCode.java:171)
at org.python.core.PyBaseCode.call(PyBaseCode.java:139)
at org.python.core.PyFunction.__call__(PyFunction.java:413)
at org.python.pycode._pyx33.nmEnroll$102(<iostream>:1712) at org.python.pycode._pyx33.call_function(<iostream>) at org.python.core.PyTableCode.call(PyTableCode.java:171)
at org.python.core.PyBaseCode.call(PyBaseCode.java:154)
at org.python.core.PyFunction.__call__(PyFunction.java:423)
at org.python.pycode._pyx32.f$0(/u01/domains/add-server.py:23)
at org.python.pycode._pyx32.call_function(/u01/domains/add-server.py)
at org.python.core.PyTableCode.call(PyTableCode.java:171)
at org.python.core.PyCode.call(PyCode.java:18)
at org.python.core.Py.runCode(Py.java:1614)
at org.python.util.PythonInterpreter.execfile(PythonInterpreter.java:296)
at weblogic.management.scripting.WLST.main(WLST.java:192) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at weblogic.WLST.main(WLST.java:47)
Caused by: weblogic.security.internal.encryption.EncryptionServiceException: com.rsa.jsafe.JSAFE_PaddingException: Invalid padding. at weblogic.security.internal.encryption.JSafeEncryptionServiceImpl.decryptBytes(JSafeEncryptionServiceImpl.java:144) at weblogic.security.internal.encryption.JSafeEncryptionServiceImpl.decryptBytes(JSafeEncryptionServiceImpl.java:177)
at weblogic.security.internal.encryption.ClearOrEncryptedService.decryptBytes(ClearOrEncryptedService.java:129)
at weblogic.management.scripting.NodeManagerService.decrypt(NodeManagerService.java:88)
at weblogic.management.scripting.NodeManagerService.nmEnrollMachine(NodeManagerService.java:130)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
__main__.WLSTException: Error occurred while performing nmEnroll : Problem occurred while encrypting a value : com.rsa.jsafe.JSAFE_PaddingException: Invalid padding.
Use dumpStack() to view the full stacktrace :
```

**Comment by sanjaymantoor** [comment]
This issue is specific to WLS 14.1.1.0.0 . There was a change in 14.1.1 where the SerializedSystemIni.dat will not be automatically downloaded from the admin server when a managed server node is added. The user will have to copy the file over from the admin server to each managed server node. 
Refer nmEnroll section at https://docs.oracle.com/en/middleware/standalone/weblogic-server/14.1.1.0/wlstc/reference.html#GUID-F41B3A7D-3291-4435-B149-7F821F26AD41

**Comment by sanjaymantoor** [comment]
With respect to copying SerializedSystemIni.dat, changes are available at https://github.com/sanjaymantoor/arm-oraclelinux-wls-cluster/tree/issue89

**Comment by edburns** [comment]
```
Thanks Sanjay, Jacob, and Galia,

I’ve looked at Sanjay’s fix and have two questions:

1.	It seems like this fix must only be enacted when the WLS version is 14.1.1 and later.  Please confirm.
2.	I would like to try to avoid having a dependency on the presence of a specific file in some fileshare somewhere that we copy at deployment time.  Can’t we do this instead?
a.	Base64 encode SerializedSystemIni.dat.
b.	Put the Base64 encoded SerializedSystemIni.dat into the setup{Cluster,Admin,DynamicCluster}Domain.sh.
c.	Add logic to setup{Cluster,Admin,DynamicCluster}Domain.sh to
i.	write it to a file via heredoc.
ii.	Base64 decode it to SerializedSystemIni.dat.
d.	Copy the file where it needs to go and do whatever else we need to do.
This way we don’t need to 
1.	Pass additional arguments to the setup{Cluster,Admin,DynamicCluster}Domain.sh script
2.	Set up a fileshare, including cifs-utils.
I’ve also put this in the issue #89.

Ed

```

**Comment by galiacheng** [comment]
@sanjaymantoor @edburns I applied Sanjay's fix in [cluster offer](https://github.com/wls-eng/arm-oraclelinux-wls-cluster/pull/43) and [dynamic cluster offer](https://github.com/wls-eng/arm-oraclelinux-wls-dynamic-cluster/pull/35) and tested with wls 14 and wls 12, please review.

**Comment by edburns** [comment]
I verified this and am able to successfully deploy WLS 14.  Woohoo, Java EE 8 on Azure!
